In [1]:
import numpy as np
import pandas as pd
from hbic import Hbic
import hbic.utils.metrics as measure

In [2]:
a = np.random.randint(0,3, (10, 10))
res = Hbic(min_cols = 2, min_rows = 2, reduction = "selection", n_clusters = 1)
bic = res.fit_predict(a)
bic, res.score

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [3]:
print("The identified bicluster is \n", a[np.ix_(bic[0][0], bic[0][1])])

The identified bicluster is 
 [[1 0 0]
 [1 0 0]
 [1 0 0]]


In [4]:
datafile = "datasets/het-data/hn3/number_3_10_data.csv"
varfile = "datasets/het-data/hn3/number_3_10_vars.csv"
#mapping categorical variables to their int id
df = pd.read_csv(datafile)
for i in df.columns:
    if pd.api.types.is_string_dtype(df[i]):
        df[i] = df[i].astype("category").cat.codes
var_type = pd.read_csv(varfile)
var_type = list(var_type["var_dtype"])
arr = df.to_numpy()

res = hbic.Hbic(min_rows = .03, min_cols = .03, verbose = True, reduction = "auto_select") 
bic = res.fit_predict(arr, var_type)
ref_bic = measure.get_ref_biclusters(3, arr.shape)


measure.prelic_relevance(bic, ref_bic), measure.prelic_recovery(bic, ref_bic),  measure.l_and_w(bic,ref_bic), measure.ayadi(bic, ref_bic) 

100%|████████████████████████████████████████████████████████████████████████████████| 300/300 [00:36<00:00,  8.26it/s]


(0.6907837311256366, 1.0, 0.6717667871123155, 0.5187065148640102)

In [5]:
df = pd.read_csv("datasets/padilha_constant/original/original1.txt", delimiter='\t')
df = df.drop('GENES', axis = 1)
arr = df.to_numpy()
res = hbic.Hbic( verbose = True, reduction = "merge", n_clusters = 1) 
bic = res.fit_predict(arr)
len(bic)

100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [00:11<00:00, 17.72it/s]


1