In [7]:
import numpy as np
import pandas as pd
from hbic import Hbic
import hbic.utils.metrics as measure

In [8]:
a = np.random.randint(0,3, (10, 10))
res = Hbic(min_cols = 2, min_rows = 2, reduction = "pareto", n_clusters = 1)
bic = res.fit_predict(a)
bic

[(array([False,  True, False, False,  True, False, False, False, False,
         False]),
  array([False,  True, False, False,  True, False,  True, False,  True,
         False])),
 (array([ True, False, False, False, False, False, False, False, False,
          True]),
  array([False, False, False,  True, False,  True,  True,  True, False,
         False])),
 (array([False,  True, False, False, False, False, False,  True, False,
         False]),
  array([False, False, False, False, False,  True, False, False,  True,
          True])),
 (array([False, False,  True, False, False, False, False,  True, False,
         False]),
  array([ True,  True, False, False,  True, False, False, False, False,
         False])),
 (array([ True, False, False, False, False, False, False, False,  True,
         False]),
  array([False, False, False,  True,  True, False, False, False,  True,
         False])),
 (array([False, False, False,  True, False,  True, False, False, False,
         False]),
  arr

In [9]:
print("The first identified bicluster has values \n", a[np.ix_(bic[0][0], bic[0][1])])

The first identified bicluster has values 
 [[0 0 0 0]
 [0 0 0 0]]


In [10]:
datafile = "tests\datasets\GBIC\EXP1_Heterogeneity_Level\HL0\hdataset_exp1_HL0_101_data.tsv"
#mapping categorical variables to their int id
df = pd.read_csv(datafile, sep = "\t", index_col = 0)
arr = df.to_numpy()

res = Hbic(min_rows = .03, min_cols = .03, verbose = True, reduction = "auto_select") 
bic = res.fit_predict(arr)
print("The first identified bicluster has values \n", arr[np.ix_(bic[0][0], bic[0][1])])

100%|██████████| 500/500 [00:08<00:00, 61.50it/s]

The first identified bicluster has values 
 [[ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]
 [ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]
 [ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]
 ...
 [ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]
 [ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]
 [ 0.13  4.22 -1.54 ... -1.17  8.68 -2.95]]
